name: Semgrep Scorecard

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Benchmark
      run: |
        mvn compile
        # ./runBenchmark.sh
    - name: Generate Scorecard
      run: |
        ./scripts/runSemgrep.sh 
        ./createScorecards.sh
    - name: Archive Scorecard
      uses: actions/upload-artifact@v3
      with:
        name: owasp-benchmark-scorecard
        path: |
          scorecard/
          results/
